name: CI for Next.js with Docker

on:
  push:
    branches:
      - main  # Exécute la CI sur chaque push vers la branche `main`.
  pull_request:
    branches:
      - main  # Exécute la CI sur chaque PR vers `main`.

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t nextjs-docker ./nextjs-docker

      # Tester l'application
      - name: Run tests
        run: echo "No tests to run"

      # Optionnel : Supprimer les conteneurs pour libérer de l'espace
      - name: Clean up
        run: docker system prune -f
